In [ ]:
import torch
print(torch.__version__)

2.9.0+cpu


In [ ]:
if torch.cuda.is_available():
    print("cuda is available")
    print(torch.cuda.get_device_name(0))
else:
    print("cuda is not available")

cuda is available
Tesla T4


## Creating a Tensor

In [ ]:
# using empty, it will create empty tensor with
# garbage value
a = torch.empty(2, 3)
a

tensor([[2.8542e-02, 4.3091e-41, 6.0479e-33],
        [0.0000e+00, 6.0479e-33, 0.0000e+00]])

In [ ]:
# check type
type(a)

torch.Tensor

In [ ]:
# use of zeros and ones

b = torch.zeros(2, 3)
c = torch.ones(2, 3)
print(b, c)

tensor([[0., 0., 0.],
        [0., 0., 0.]]) tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [ ]:
# using rand

torch.rand(2, 3)

tensor([[0.7440, 0.6711, 0.7593],
        [0.7442, 0.7546, 0.4143]])

In [ ]:
# use of manual_seed, this makes torch.rand to
# generate constant value at every call.

torch.manual_seed(100)
torch.rand(2, 3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [ ]:
torch.manual_seed(100)
torch.rand(2, 3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [ ]:
# using torch
torch.tensor([[1, 2, 3], [4, 5, 6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
# other ways
torch.arange(0, 10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
torch.linspace(0, 10, 10)

tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])

In [ ]:
# Identity Matrix
torch.eye(3)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [ ]:
# torch.full
torch.full((3, 3), 10)

tensor([[10, 10, 10],
        [10, 10, 10],
        [10, 10, 10]])

## Tensor Shapes

In [ ]:
x = torch.tensor([[1,2, 3], [4, 5, 6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
x.shape

torch.Size([2, 3])

In [ ]:
# create a tensor using shape of other tensor
torch.empty_like(x)

tensor([[      138930112, 132070978014896,               1],
        [              6,               0,               0]])

In [ ]:

torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [ ]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [ ]:
print(x.dtype)

torch.rand_like(x, dtype=torch.float64)

torch.int64


tensor([[0.8319, 0.0074, 0.7866],
        [0.9999, 0.0422, 0.6941]], dtype=torch.float64)

## Tensor Data Types

In [ ]:
# find data type
x.dtype

torch.int64

In [ ]:
# assign data type while creating a variable
torch.tensor([1.0, 2.0, 3.0], dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [ ]:
torch.tensor([1, 2, 3], dtype=torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

In [ ]:
# change data type of tensor using to()
x.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

# Mathematical Operations

## 1. Scalar Operation

In [ ]:
x = torch.rand(2, 3)
x

tensor([[0.7445, 0.4892, 0.2426],
        [0.7003, 0.5277, 0.2472]])

In [ ]:
# addition
x + 2

# sustraction
x - 2

# multiplication
x * 3

# division
x / 3

# int division
(x * 100) // 3

# mod
((x * 100)//4) % 3


tensor([[1., 2., 1.],
        [0., 2., 2.]])

In [ ]:
torch.clamp(x*10, min=2, max=4) # equivalent of tf.clip_by_value()

tensor([[4.0000, 4.0000, 2.4256],
        [4.0000, 4.0000, 2.4718]])

In [ ]:
# torch.sum(), torch.mean(), torch.median(), torch.min() and torch.max()
# product(), std(),, var(), argmax(), argmin(), argsort(),

print('x: ', x)
torch.sum(x, dim=0)

x:  tensor([[0.7445, 0.4892, 0.2426],
        [0.7003, 0.5277, 0.2472]])


tensor([1.4448, 1.0169, 0.4897])

In [ ]:
torch.argsort(x, dim=1)

tensor([[2, 1, 0],
        [2, 1, 0]])

## Matrix operations

In [ ]:
# torch.transpose

In [ ]:
a = torch.tensor([[1, 2, 3], [4, 5, 6]])
b = torch.tensor([[4, 5], [1, 1], [1, 2]])

In [ ]:
torch.transpose(a, 0, 1)

tensor([[1, 4],
        [2, 5],
        [3, 6]])

# 6. Special Functions

In [ ]:
k = torch.randint(size=(2, 3), low=0, high=10, dtype=torch.float32)

In [ ]:
print(k)

torch.log(k)

tensor([[9, 7, 5],
        [9, 8, 9]])


tensor([[2.1972, 1.9459, 1.6094],
        [2.1972, 2.0794, 2.1972]])

In [ ]:
# ReLU

torch.relu(k)

tensor([[7., 9., 2.],
        [6., 7., 7.]])

In [ ]:
# Sigmoid

torch.sigmoid(k)

tensor([[0.9991, 0.9999, 0.8808],
        [0.9975, 0.9991, 0.9991]])

In [ ]:
# softmax
torch.softmax(k, dim=1)

tensor([[1.1911e-01, 8.8009e-01, 8.0254e-04],
        [1.5536e-01, 4.2232e-01, 4.2232e-01]])

# Inplace Operations

In [ ]:
m = torch.rand(2, 3)
n = torch.rand(2, 3)

In [ ]:
# adding _ afte the operation name

m.add_(n)

tensor([[2.4115, 3.1386, 3.6587],
        [3.1127, 2.6365, 2.5263]])

# Copying a Tensor

In [ ]:
a = torch.rand(2, 3)

In [ ]:
a

tensor([[0.3451, 0.0453, 0.9798],
        [0.5548, 0.6868, 0.4920]])

In [ ]:
b = a.clone()

In [ ]:
b

tensor([[0.3451, 0.0453, 0.9798],
        [0.5548, 0.6868, 0.4920]])

## Tensor operations on GPU

In [ ]:
torch.cuda.is_available()

True

In [ ]:
device = torch.device('cuda')

In [ ]:
# createing a new tensor on GPU
a = torch.rand((2, 3), device=device)

In [ ]:
a

tensor([[0.1554, 0.2234, 0.2462],
        [0.6009, 0.0998, 0.2430]], device='cuda:0')

In [ ]:
# moving an existing tensor on GPU
b = torch.rand(2, 3)

In [ ]:
b = b.to(device)

In [ ]:
b

tensor([[0.3157, 0.5252, 0.9072],
        [0.3705, 0.3920, 0.4471]], device='cuda:0')

## Reshapping tensors

In [ ]:
a = torch.rand((2, 4, 3))

In [ ]:
a

tensor([[[0.6884, 0.2009, 0.3071],
         [0.7403, 0.9258, 0.2554],
         [0.2045, 0.5035, 0.0745],
         [0.2072, 0.7070, 0.9697]],

        [[0.0565, 0.4058, 0.6713],
         [0.0332, 0.0486, 0.4421],
         [0.2714, 0.7646, 0.0257],
         [0.4365, 0.4823, 0.6442]]])

In [ ]:
# Transpose: swaps exactly two specified dimensions
a.transpose(1, 0)


tensor([[[0.6884, 0.2009, 0.3071],
         [0.0565, 0.4058, 0.6713]],

        [[0.7403, 0.9258, 0.2554],
         [0.0332, 0.0486, 0.4421]],

        [[0.2045, 0.5035, 0.0745],
         [0.2714, 0.7646, 0.0257]],

        [[0.2072, 0.7070, 0.9697],
         [0.4365, 0.4823, 0.6442]]])

In [ ]:
a.shape

torch.Size([2, 4, 3])

In [ ]:
# permute: reorders all dimentions of a tensor
a.permute(2, 0, 1)

tensor([[[0.6884, 0.7403, 0.2045, 0.2072],
         [0.0565, 0.0332, 0.2714, 0.4365]],

        [[0.2009, 0.9258, 0.5035, 0.7070],
         [0.4058, 0.0486, 0.7646, 0.4823]],

        [[0.3071, 0.2554, 0.0745, 0.9697],
         [0.6713, 0.4421, 0.0257, 0.6442]]])

In [ ]:
a.flatten()

tensor([2.8542e-02, 4.3091e-41, 6.0479e-33, 0.0000e+00, 6.0479e-33, 0.0000e+00])

In [ ]:
# squeeze and unsqueeze
a = torch.rand((2, 1, 3))

In [ ]:
a.shape

torch.Size([2, 1, 3])

In [ ]:
a.squeeze().shape

torch.Size([2, 3])

In [ ]:
a.unsqueeze(0).shape

torch.Size([1, 2, 1, 3])

## NumPy and PyTorch

In [ ]:
import numpy as np

In [ ]:
a = torch.rand((3, 3))
type(a)

torch.Tensor

In [ ]:
b = a.numpy()

In [ ]:
type(b)

numpy.ndarray

In [ ]:
c = torch.from_numpy(b)

In [ ]:
type(c)
print(type(c), type(b))

<class 'torch.Tensor'> <class 'numpy.ndarray'>
